import type {
  Track,
  Podcast,
  Audiobook,
  Scripture,
  RejoiceEvent,
  Artist,
  Playlist,
  DiscoveryPath,
  AnyContent,
  Disclosure,
} from "./types";

const humanDefault: Disclosure = {
  human: true,
  aiAssisted: "No",
  syntheticVocals: false,
  familySuitable: true,
};

/* --------------------------------- tracks -------------------------------- */

export const tracks: Track[] = [
  {
    id: "t-psalm42",
    kind: "track",
    title: "Psalm 42: Deep Calls",
    artist: "The Psalms Project",
    artistId: "a-psalms",
    album: "Songs of Ascent",
    duration: 254,
    category: "Worship",
    mood: "Longing",
    themes: ["Lament", "Hope", "Longing for God"],
    scripture: ["Psalm 42"],
    artwork: "deep",
    disclosure: humanDefault,
    supportEligible: true,
    lyricsExcerpt:
      "As the deer pants for the water, so my soul longs after You…",
    description:
      "A sung setting of Psalm 42 that moves from lament into hope.",
  },
  {
    id: "t-throne",
    kind: "track",
    title: "Before the Throne",
    artist: "City Light Worship",
    artistId: "a-citylight",
    album: "Worship Night Live",
    duration: 312,
    category: "Worship",
    mood: "Reverent",
    themes: ["Adoration", "Grace", "Assurance"],
    scripture: ["Hebrews 4", "Revelation 5"],
    artwork: "blue",
    disclosure: humanDefault,
    supportEligible: true,
    description: "A congregational anthem of assurance and adoration.",
  },
  {
    id: "t-mercy",
    kind: "track",
    title: "Morning Mercy",
    artist: "Grace & Harp",
    artistId: "a-grace",
    album: "Morning & Evening",
    duration: 221,
    category: "Acoustic",
    mood: "Gentle",
    themes: ["Faithfulness", "Hope", "New mercies"],
    scripture: ["Lamentations 3"],
    artwork: "dawn",
    disclosure: humanDefault,
    supportEligible: true,
    description: "A quiet acoustic meditation on mercies new every morning.",
  },
  {
    id: "t-holy",
    kind: "track",
    title: "Holy, Holy, Holy",
    artist: "Kingdom Choir",
    artistId: "a-kingdom",
    album: "Hymns of the Church",
    duration: 286,
    category: "Hymn",
    mood: "Majestic",
    themes: ["Holiness", "Trinity", "Worship"],
    scripture: ["Isaiah 6", "Revelation 4"],
    artwork: "gold",
    disclosure: humanDefault,
    supportEligible: true,
    description: "The beloved hymn arranged for full choir.",
  },
  {
    id: "t-night",
    kind: "track",
    title: "Songs in the Night",
    artist: "Grace & Harp",
    artistId: "a-grace",
    album: "Morning & Evening",
    duration: 268,
    category: "Acoustic",
    mood: "Comforting",
    themes: ["Lament", "Comfort", "Trust"],
    scripture: ["Job 35", "Psalm 77"],
    artwork: "night",
    disclosure: humanDefault,
    supportEligible: true,
    description: "Comfort for the sleepless and the sorrowing.",
  },
  {
    id: "t-rest",
    kind: "track",
    title: "Christ Our Rest",
    artist: "City Light Worship",
    artistId: "a-citylight",
    album: "Worship Night Live",
    duration: 297,
    category: "Worship",
    mood: "Peaceful",
    themes: ["Rest in Christ", "Adoption", "Grace"],
    scripture: ["Matthew 11", "Romans 8"],
    artwork: "sage",
    disclosure: humanDefault,
    supportEligible: true,
    description: "An invitation to rest, drawn from Matthew 11 and Romans 8.",
  },
  {
    id: "t-valley",
    kind: "track",
    title: "The Valley of Hope",
    artist: "The Psalms Project",
    artistId: "a-psalms",
    album: "Songs of Ascent",
    duration: 243,
    category: "Worship",
    mood: "Hopeful",
    themes: ["Lament", "Hope", "Restoration"],
    scripture: ["Psalm 23", "Hosea 2"],
    artwork: "stone",
    disclosure: humanDefault,
    supportEligible: true,
    description: "Walking through the valley toward the hope of restoration.",
  },
  {
    id: "t-fount",
    kind: "track",
    title: "Come Thou Fount — Acoustic",
    artist: "Grace & Harp",
    artistId: "a-grace",
    album: "Hymns Reimagined",
    duration: 274,
    category: "Hymn",
    mood: "Warm",
    themes: ["Grace", "Gratitude", "Faithfulness"],
    scripture: ["1 Samuel 7"],
    artwork: "gold",
    disclosure: {
      human: true,
      aiAssisted: "Yes — production assistance disclosed",
      syntheticVocals: false,
      familySuitable: true,
      note: "AI tools assisted with mixing and mastering. All vocals and instruments are human-performed.",
    },
    supportEligible: true,
    description:
      "A warm acoustic hymn arrangement. Includes a disclosed example of AI-assisted production.",
  },
];

/* -------------------------------- podcasts ------------------------------- */

export const podcasts: Podcast[] = [
  {
    id: "p-narrow",
    kind: "podcast",
    show: "The Narrow Way Podcast",
    host: "Jonah & Mara Reese",
    episode: "Walking the Narrow Way Together",
    title: "Walking the Narrow Way Together",
    duration: 2940,
    themes: ["Discipleship", "Perseverance"],
    scripture: ["Matthew 7"],
    artwork: "slate",
    transcriptAvailable: true,
    disclosure: humanDefault,
    supportEligible: true,
    description: "On discipleship, cost, and joy in following Jesus.",
  },
  {
    id: "p-table",
    kind: "podcast",
    show: "Table & Word",
    host: "Pastor Eli Hart",
    episode: "Hospitality as Worship",
    title: "Hospitality as Worship",
    duration: 2510,
    themes: ["Community", "Hospitality"],
    scripture: ["Romans 12"],
    artwork: "dawn",
    transcriptAvailable: true,
    disclosure: humanDefault,
    supportEligible: true,
    description: "How the shared table forms the people of God.",
  },
  {
    id: "p-households",
    kind: "podcast",
    show: "Faithful Households",
    host: "The Adeyemi Family",
    episode: "Praying in Sorrow",
    title: "Faithful Households: Praying in Sorrow",
    duration: 2185,
    themes: ["Lament", "Family", "Prayer"],
    scripture: ["Psalm 42", "Psalm 6"],
    artwork: "night",
    transcriptAvailable: true,
    disclosure: humanDefault,
    supportEligible: true,
    description: "Teaching households to pray honestly through grief.",
  },
  {
    id: "p-pilgrims",
    kind: "podcast",
    show: "Theology for Pilgrims",
    host: "Dr. Ruth Calloway",
    episode: "Adoption in Christ",
    title: "Theology for Pilgrims: Adoption in Christ",
    duration: 3120,
    themes: ["Adoption", "Grace", "Identity"],
    scripture: ["Romans 8", "Ephesians 1"],
    artwork: "blue",
    transcriptAvailable: true,
    disclosure: humanDefault,
    supportEligible: true,
    description: "What it means to be adopted as children of God.",
  },
  {
    id: "p-mission",
    kind: "podcast",
    show: "Mission Field Notes",
    host: "Sam Okoro",
    episode: "Worship Among the Nations",
    title: "Mission Field Notes: Worship Among the Nations",
    duration: 2760,
    themes: ["Mission", "Worship", "Nations"],
    scripture: ["Revelation 7", "Psalm 96"],
    artwork: "sage",
    transcriptAvailable: false,
    disclosure: humanDefault,
    supportEligible: true,
    description: "Stories of worship rising from the global Church.",
  },
  {
    id: "p-letters",
    kind: "podcast",
    show: "Letters to the Church",
    host: "Pastor Eli Hart",
    episode: "On Suffering and Endurance",
    title: "Letters to the Church: On Suffering and Endurance",
    duration: 2890,
    themes: ["Suffering", "Endurance", "Hope"],
    scripture: ["Romans 5", "James 1"],
    artwork: "stone",
    transcriptAvailable: true,
    disclosure: humanDefault,
    supportEligible: true,
    description: "A pastoral letter on enduring suffering with hope.",
  },
];

/* ------------------------------- audiobooks ------------------------------ */

export const audiobooks: Audiobook[] = [
  {
    id: "b-prayer",
    kind: "audiobook",
    title: "The Life of Prayer",
    author: "Margaret Ellison",
    narrator: "Clare Whitfield",
    chapters: 12,
    publisher: "Emmaus Audio",
    duration: 25200,
    themes: ["Prayer", "Communion with God"],
    scripture: ["Matthew 6", "Luke 11"],
    artwork: "blue",
    disclosure: humanDefault,
    supportEligible: true,
    description: "A classic-style guide to a life of prayer.",
  },
  {
    id: "b-pilgrim",
    kind: "audiobook",
    title: "Pilgrim Songs",
    author: "Thomas Vane",
    narrator: "David Mercer",
    chapters: 9,
    publisher: "Emmaus Audio",
    duration: 19800,
    themes: ["Pilgrimage", "Hope", "Psalms"],
    scripture: ["Psalm 120", "Psalm 121"],
    artwork: "stone",
    disclosure: humanDefault,
    supportEligible: true,
    description: "Reflections on the Songs of Ascent.",
  },
  {
    id: "b-valley",
    kind: "audiobook",
    title: "Grace in the Valley",
    author: "Naomi Brand",
    narrator: "Naomi Brand",
    chapters: 10,
    publisher: "River & Table",
    duration: 21600,
    themes: ["Lament", "Suffering", "Hope", "Rest in Christ"],
    scripture: ["Psalm 23", "Romans 8"],
    artwork: "sage",
    disclosure: humanDefault,
    supportEligible: true,
    description: "Finding grace while walking through grief.",
  },
  {
    id: "b-household",
    kind: "audiobook",
    title: "The Household of Faith",
    author: "The Adeyemi Family",
    narrator: "Tunde Adeyemi",
    chapters: 8,
    publisher: "River & Table",
    duration: 18000,
    themes: ["Family", "Discipleship", "Worship"],
    scripture: ["Deuteronomy 6", "Ephesians 6"],
    artwork: "dawn",
    disclosure: humanDefault,
    supportEligible: true,
    description: "Discipleship and worship in the Christian home.",
  },
  {
    id: "b-worship",
    kind: "audiobook",
    title: "Letters on Worship",
    author: "Dr. Ruth Calloway",
    narrator: "Clare Whitfield",
    chapters: 11,
    publisher: "Emmaus Audio",
    duration: 23400,
    themes: ["Worship", "Theology", "Liturgy"],
    scripture: ["John 4", "Psalm 95"],
    artwork: "gold",
    disclosure: humanDefault,
    supportEligible: true,
    description: "A theology of worship in accessible letters.",
  },
  {
    id: "b-comfort",
    kind: "audiobook",
    title: "Christ Our Comfort",
    author: "Margaret Ellison",
    narrator: "David Mercer",
    chapters: 7,
    publisher: "River & Table",
    duration: 16200,
    themes: ["Comfort", "Suffering", "Hope"],
    scripture: ["2 Corinthians 1", "Isaiah 53"],
    artwork: "night",
    disclosure: humanDefault,
    supportEligible: true,
    description: "Comfort for the afflicted from the God of all comfort.",
  },
];

/* ------------------------------- scripture ------------------------------- */

export const scriptures: Scripture[] = [
  {
    id: "s-ps23",
    kind: "scripture",
    title: "Psalm 23",
    book: "Psalms",
    chapter: "23",
    reader: "Sample reader",
    duration: 180,
    themes: ["Comfort", "Shepherd", "Rest in Christ"],
    scripture: ["Psalm 23"],
    artwork: "sage",
    disclosure: { ...humanDefault },
    linked: ["t-valley", "b-valley"],
    reflection: "Where do you most need the Shepherd's leading today?",
    description: "The Shepherd Psalm.",
  },
  {
    id: "s-ps42",
    kind: "scripture",
    title: "Psalm 42",
    book: "Psalms",
    chapter: "42",
    reader: "Sample reader",
    duration: 165,
    themes: ["Lament", "Hope", "Longing for God"],
    scripture: ["Psalm 42"],
    artwork: "deep",
    disclosure: { ...humanDefault },
    linked: ["t-psalm42", "p-households", "b-prayer"],
    reflection: "What does it look like to hope in God amid sorrow?",
    description: "As the deer pants for the water.",
  },
  {
    id: "s-rom8",
    kind: "scripture",
    title: "Romans 8",
    book: "Romans",
    chapter: "8",
    reader: "Sample reader",
    duration: 420,
    themes: ["Adoption", "Hope", "Rest in Christ", "Assurance"],
    scripture: ["Romans 8"],
    artwork: "blue",
    disclosure: { ...humanDefault },
    linked: ["t-rest", "p-pilgrims", "b-valley"],
    reflection: "How does adoption in Christ change how you face suffering?",
    description: "No condemnation, and nothing can separate us.",
  },
  {
    id: "s-john15",
    kind: "scripture",
    title: "John 15",
    book: "John",
    chapter: "15",
    reader: "Sample reader",
    duration: 300,
    themes: ["Abiding", "Love", "Fruitfulness"],
    scripture: ["John 15"],
    artwork: "sage",
    disclosure: { ...humanDefault },
    linked: ["t-throne", "b-worship"],
    reflection: "What would it look like to abide more deeply this week?",
    description: "I am the vine, you are the branches.",
  },
  {
    id: "s-isa53",
    kind: "scripture",
    title: "Isaiah 53",
    book: "Isaiah",
    chapter: "53",
    reader: "Sample reader",
    duration: 240,
    themes: ["Suffering", "Atonement", "Hope"],
    scripture: ["Isaiah 53"],
    artwork: "night",
    disclosure: { ...humanDefault },
    linked: ["t-night", "b-comfort"],
    reflection: "Sit with the suffering Servant who carries our sorrows.",
    description: "The suffering Servant.",
  },
  {
    id: "s-eph1",
    kind: "scripture",
    title: "Ephesians 1",
    book: "Ephesians",
    chapter: "1",
    reader: "Sample reader",
    duration: 270,
    themes: ["Adoption", "Grace", "Blessing"],
    scripture: ["Ephesians 1"],
    artwork: "gold",
    disclosure: { ...humanDefault },
    linked: ["p-pilgrims", "b-worship"],
    reflection: "Count the spiritual blessings named in this chapter.",
    description: "Every spiritual blessing in Christ.",
  },
  {
    id: "s-rev5",
    kind: "scripture",
    title: "Revelation 5",
    book: "Revelation",
    chapter: "5",
    reader: "Sample reader",
    duration: 210,
    themes: ["Worship", "The Lamb", "Nations"],
    scripture: ["Revelation 5"],
    artwork: "deep",
    disclosure: { ...humanDefault },
    linked: ["t-throne", "t-holy", "p-mission"],
    reflection: "Join the song of every tribe and tongue before the Lamb.",
    description: "Worthy is the Lamb.",
  },
];

/* --------------------------------- events -------------------------------- */

export const events: RejoiceEvent[] = [
  {
    id: "e-psalms",
    kind: "event",
    title: "Psalms & Prayer Night",
    host: "The Psalms Project",
    city: "Sydney",
    venue: "Harbour Church Hall",
    date: "Oct 17, 2026",
    time: "7:00 PM",
    themes: ["Lament", "Hope", "Prayer"],
    relatedArtists: ["a-psalms"],
    artwork: "deep",
    familyFriendly: true,
    description: "An evening of sung Psalms and guided prayer.",
  },
  {
    id: "e-citywide",
    kind: "event",
    title: "Citywide Worship Gathering",
    host: "City Light Worship",
    city: "Nashville",
    venue: "Downtown Auditorium",
    date: "Nov 7, 2026",
    time: "6:30 PM",
    themes: ["Adoration", "Unity"],
    relatedArtists: ["a-citylight"],
    artwork: "blue",
    familyFriendly: true,
    description: "Churches across the city gather to worship together.",
  },
  {
    id: "e-acoustic",
    kind: "event",
    title: "Acoustic Hymns Evening",
    host: "Grace & Harp",
    city: "London",
    venue: "St. Aldate's Hall",
    date: "Nov 21, 2026",
    time: "7:30 PM",
    themes: ["Hymns", "Rest in Christ"],
    relatedArtists: ["a-grace"],
    artwork: "gold",
    familyFriendly: true,
    description: "An intimate night of reimagined hymns.",
  },
  {
    id: "e-nations",
    kind: "event",
    title: "Worship for the Nations",
    host: "Mission Field Notes",
    city: "Lagos",
    venue: "Grace Centre",
    date: "Dec 5, 2026",
    time: "5:00 PM",
    themes: ["Mission", "Nations", "Worship"],
    artwork: "sage",
    familyFriendly: true,
    description: "A multilingual celebration of global worship.",
  },
  {
    id: "e-family",
    kind: "event",
    title: "Family Scripture & Song Night",
    host: "Faithful Households",
    city: "Singapore",
    venue: "Riverside Chapel",
    date: "Dec 12, 2026",
    time: "4:00 PM",
    themes: ["Family", "Scripture", "Worship"],
    artwork: "dawn",
    familyFriendly: true,
    description: "A gentle evening for households of all ages.",
  },
  {
    id: "e-advent",
    kind: "event",
    title: "Advent Songs Live",
    host: "Kingdom Choir",
    city: "New York",
    venue: "Old Trinity Hall",
    date: "Dec 19, 2026",
    time: "8:00 PM",
    themes: ["Advent", "Hope", "Worship"],
    relatedArtists: ["a-kingdom"],
    artwork: "night",
    familyFriendly: true,
    description: "Choral Advent worship awaiting the coming King.",
  },
];

/* --------------------------------- artists ------------------------------- */

export const artists: Artist[] = [
  {
    id: "a-grace",
    kind: "artist",
    name: "Grace & Harp",
    type: "Artist",
    bio: "A folk-worship duo crafting gentle hymn arrangements and original songs for the weary and the hopeful.",
    location: "London, UK",
    traditions: ["Hymnody", "Folk worship"],
    artwork: "gold",
    featuredTrackId: "t-mercy",
    trackIds: ["t-mercy", "t-night", "t-fount"],
    eventIds: ["e-acoustic"],
    humanArtistry:
      "Grace & Harp is presented as a human-created artist project. Any material AI assistance, synthetic vocals, or translated recordings would be disclosed on individual works.",
    aiUse:
      "One release ('Come Thou Fount — Acoustic') discloses AI-assisted production. All vocals and instruments are human-performed.",
    scriptureThemes: ["Grace", "Faithfulness", "Rest in Christ"],
    supportEligible: true,
  },
  {
    id: "a-psalms",
    kind: "artist",
    name: "The Psalms Project",
    type: "Ministry",
    bio: "A worship collective setting the Psalms to music for congregational singing across the global Church.",
    location: "Sydney, AU",
    traditions: ["Psalmody"],
    artwork: "deep",
    featuredTrackId: "t-psalm42",
    trackIds: ["t-psalm42", "t-valley"],
    eventIds: ["e-psalms"],
    humanArtistry:
      "The Psalms Project is a human-created worship ministry. Disclosures appear on individual works.",
    aiUse: "No AI-generated vocals or synthetic personas.",
    scriptureThemes: ["Lament", "Hope", "Psalms"],
    supportEligible: true,
  },
  {
    id: "a-citylight",
    kind: "artist",
    name: "City Light Worship",
    type: "Church",
    bio: "The worship team of a city church, writing songs of assurance and rest for Sunday gatherings.",
    location: "Nashville, US",
    traditions: ["Contemporary worship"],
    artwork: "blue",
    featuredTrackId: "t-throne",
    trackIds: ["t-throne", "t-rest"],
    eventIds: ["e-citywide"],
    humanArtistry:
      "City Light Worship is a human-created church worship team. All worship leaders are real people, never synthetic.",
    aiUse: "No synthetic worship leaders. No AI-generated vocals.",
    scriptureThemes: ["Adoption", "Rest in Christ", "Grace"],
    supportEligible: true,
  },
  {
    id: "a-kingdom",
    kind: "artist",
    name: "Kingdom Choir",
    type: "Artist",
    bio: "A choral ensemble carrying the great hymns of the Church into a new generation.",
    location: "New York, US",
    traditions: ["Choral", "Hymnody"],
    artwork: "stone",
    featuredTrackId: "t-holy",
    trackIds: ["t-holy"],
    eventIds: ["e-advent"],
    humanArtistry: "Kingdom Choir is a human-created choral project.",
    aiUse: "No AI-generated vocals or synthetic personas.",
    scriptureThemes: ["Holiness", "Advent", "Worship"],
    supportEligible: true,
  },
  {
    id: "a-emmaus",
    kind: "artist",
    name: "Emmaus Audio",
    type: "Publisher",
    bio: "An audiobook publisher devoted to classic and contemporary works on prayer, worship, and the Christian life.",
    location: "Edinburgh, UK",
    artwork: "blue",
    trackIds: [],
    humanArtistry:
      "Emmaus Audio publishes works narrated by human readers. Any AI narration would be disclosed.",
    aiUse: "Human narration. Translations and any synthetic narration disclosed per title.",
    scriptureThemes: ["Prayer", "Worship"],
    supportEligible: true,
  },
  {
    id: "a-narrow",
    kind: "artist",
    name: "The Narrow Way Podcast",
    type: "Podcast",
    bio: "Honest conversations on discipleship, perseverance, and joy in following Jesus.",
    location: "Cape Town, ZA",
    artwork: "slate",
    humanArtistry: "Hosted by real people; no synthetic personas.",
    aiUse: "No AI-generated voices.",
    scriptureThemes: ["Discipleship", "Perseverance"],
    supportEligible: true,
  },
];

/* -------------------------------- playlists ------------------------------ */

export const playlists: Playlist[] = [
  {
    id: "pl-family-morning",
    kind: "playlist",
    title: "Family Morning Worship",
    description: "Gentle songs to begin the day together.",
    artwork: "dawn",
    itemIds: ["t-mercy", "t-throne", "s-ps23"],
    family: true,
  },
  {
    id: "pl-bedtime",
    kind: "playlist",
    title: "Bedtime Psalms",
    description: "Calm Scripture and song for the end of the day.",
    artwork: "night",
    itemIds: ["s-ps23", "t-night", "s-ps42"],
    family: true,
  },
  {
    id: "pl-car",
    kind: "playlist",
    title: "Scripture for the Car",
    description: "Short Scripture readings for the school run.",
    artwork: "sage",
    itemIds: ["s-ps23", "s-john15", "s-eph1"],
    family: true,
  },
  {
    id: "pl-sunday",
    kind: "playlist",
    title: "Songs for Sunday",
    description: "Prepare your heart for gathered worship.",
    artwork: "blue",
    itemIds: ["t-throne", "t-holy", "t-rest"],
    family: true,
  },
  {
    id: "pl-catechism",
    kind: "playlist",
    title: "Catechism & Song",
    description: "Truth set to music for growing households.",
    artwork: "gold",
    itemIds: ["t-holy", "s-eph1", "t-rest"],
    family: true,
  },
  {
    id: "pl-rom8",
    kind: "playlist",
    title: "Romans 8 Listening Path",
    description: "Music and teaching gathered around Romans 8.",
    artwork: "blue",
    itemIds: ["s-rom8", "t-rest", "p-pilgrims", "b-valley"],
  },
];

/* ----------------------------- discovery paths --------------------------- */

export const discoveryPaths: DiscoveryPath[] = [
  {
    id: "d-lament",
    label: "Lament and Hope",
    kind: "theme",
    selection: "Lament and Hope",
    explanation:
      "Rejoice connects songs, Scripture, podcasts, books, and gatherings through biblical themes and theological context.",
    itemIds: ["s-ps42", "t-psalm42", "b-prayer", "p-households", "e-psalms"],
  },
  {
    id: "d-rom8",
    label: "Romans 8",
    kind: "passage",
    selection: "Romans 8",
    explanation:
      "From a single passage, move across Scripture, song, teaching, books, artists, and playlists.",
    itemIds: ["s-rom8", "t-rest", "p-pilgrims", "b-valley", "pl-rom8"],
  },
  {
    id: "d-prayer",
    label: "Prayer and Communion with God",
    kind: "theme",
    selection: "Prayer and Communion with God",
    explanation:
      "Faithful discovery gathers prayer-shaped audio across every format.",
    itemIds: ["b-prayer", "p-households", "s-ps42", "t-mercy"],
  },
  {
    id: "d-advent",
    label: "Advent and the Coming King",
    kind: "theme",
    selection: "Advent and the Coming King",
    explanation: "An Advent listening path toward the coming King.",
    itemIds: ["e-advent", "t-holy", "s-rev5", "p-mission"],
  },
  {
    id: "d-family",
    label: "Family Worship",
    kind: "theme",
    selection: "Family Worship",
    explanation: "Calmer audio gathered for households and children.",
    itemIds: ["pl-family-morning", "s-ps23", "t-mercy", "e-family"],
  },
  {
    id: "d-rest",
    label: "Rest in Christ",
    kind: "theme",
    selection: "Rest in Christ",
    explanation: "Audio that points the weary to rest in Christ.",
    itemIds: ["t-rest", "s-rom8", "b-valley", "s-ps23"],
  },
  {
    id: "d-mission",
    label: "Mission and the Nations",
    kind: "theme",
    selection: "Mission and the Nations",
    explanation: "Worship and teaching from the global Church.",
    itemIds: ["p-mission", "s-rev5", "e-nations", "t-holy"],
  },
];

/* --------------------------------- lookups ------------------------------- */

export const allContent: AnyContent[] = [
  ...tracks,
  ...podcasts,
  ...audiobooks,
  ...scriptures,
  ...events,
];

const contentById = new Map<string, AnyContent>();
for (const c of allContent) contentById.set(c.id, c);

const artistById = new Map<string, Artist>();
for (const a of artists) artistById.set(a.id, a);

const playlistById = new Map<string, Playlist>();
for (const p of playlists) playlistById.set(p.id, p);

export function getContent(id: string): AnyContent | undefined {
  return contentById.get(id);
}

export function getArtist(id: string): Artist | undefined {
  return artistById.get(id);
}

export function getPlaylist(id: string): Playlist | undefined {
  return playlistById.get(id);
}

/** Resolve any id (content or playlist) to a display item, if present. */
export function resolveItem(id: string): AnyContent | Playlist | undefined {
  return contentById.get(id) ?? playlistById.get(id);
}
